# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mmult <- function(A, B) {
    .Call(`_emulatorr_mmult`, A, B)
}

minv <- function(M) {
    .Call(`_emulatorr_minv`, M)
}

